name: Build and Deploy Code
on: [push, pull_request]
jobs:
  job_test:
    runs-on: ubuntu-latest
    steps:
      - name: pull the repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: upgrade pip
        run: python -m pip instlal --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt

